# Generated by Django 3.2.6 on 2021-11-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='moviepicks',
            field=models.ManyToManyField(to='accounts.PickMovie'),
        ),
    ]
