# Generated by Django 3.2.6 on 2021-11-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211123_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_genre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='second_genre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
