# Generated by Django 3.2.6 on 2021-11-19 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='tag',
            new_name='tags',
        ),
    ]
