# Generated by Django 3.2.6 on 2021-11-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20211122_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='communities', to='community.Tag'),
        ),
    ]
