# Generated by Django 3.2.6 on 2021-11-25 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0006_alter_community_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_community', to=settings.AUTH_USER_MODEL),
        ),
    ]
