# Generated by Django 3.2.6 on 2021-11-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20211119_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile_path',
            field=models.TextField(null=True),
        ),
    ]
