# Generated by Django 3.2.6 on 2021-11-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20211121_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChristmasMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('overview', models.TextField()),
                ('poster_path', models.TextField()),
                ('genre_ids', models.ManyToManyField(related_name='christmasmovie_genre', to='movies.Genre')),
            ],
        ),
    ]
