# Generated by Django 3.2.6 on 2021-11-23 02:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0008_christmasmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='christmasmovie',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_christmasmovies', to=settings.AUTH_USER_MODEL),
        ),
    ]
