# Generated by Django 3.2.6 on 2021-11-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_christmasmovie_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='christmasmovie',
            name='actors',
            field=models.CharField(default='', max_length=200),
        ),
    ]
