# Generated by Django 3.2.6 on 2021-11-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_christmasmovie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='christmasmovie',
            name='popularity',
            field=models.FloatField(default=0.0),
        ),
    ]
