# Generated by Django 3.2.6 on 2021-11-23 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0011_christmasmovie_popularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChristmasReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('rank', models.FloatField()),
                ('christmasmovie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='christmasmovie_review', to='movies.movie')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
